package Objects;

public class DO_NOT_EDIT_THESE_DIRECTLY {

	/*
	 * 
	 * THIS IS A WARNING FILE TELLING YOU TO NOT DIRECTLY EDIT ANY OF THESE OBJECTS
	 * 
	 * IF CHANGES NEED TO BE MADE, EITHER SWITCH TO THE OBJECT BRANCH -> CHANGE THEM -> COMMIT -> MERGE OBJECTS INTO YOUR BRANCH
	 * 
	 * OR
	 * 
	 * CONTACT GEORGE TO CHANGE AND COMMIT, THEN MERGE
	 * 
	 * THIS ENSURES EVERYONE HAS THE SAME FILES SO CAN ACCESS THE SAME METHODS ETC
	 * 
	 * 
	 * THANK YOU :)
	 * 
	 * 
	 * 
	 */

}
