
public class LearningCancellations {

/**
 * CLASS FOR FEATURES FOR JOB CANCELLLATION
 * 
 * (1) NO' DIFFERENT ITEMS
 * THIS RANGES FROM 1 - 8 IN THE FILE
 * POSSIBLE RANGES: 1 2-3 4-5 6-7 8+ ?
 * 
 * (2) TOTAL NO. ITEMS
 * UPPER RANGE LIMIT OF (15 +) ?
 * CAN DO SOME TESTS WITH A TOTAL NO. ITEMS CALCULATOR ON TEST DATA TO VIEW SPREAD
 * 
 * (3) SPECIFIC ITEM
 * A JOB CONTAINING A SPECIFIC ITEM ID MAY BE MORE LIKELY TO BE CANCELLATION
 * TODO: DECIDE HOW TO ORGANISE THE ITEM IDS? 
 * 
 * (4) TOTAL REWARD
 * TODO: WORK OUT SUITABLE RANGES
 * TRY OUT TOTAL REWARD CALCULATOR ON SOME TEST DATA TO VIEW SPREAD
 * 
 * (5) TOTAL WEIGHT
 * TODO: WORK OUT SUITABLE RANGES
 * TRY OUT TOTAL WEIGHT CALCULATOR ON SOME TEST DATA TO VIEW SPREAD
 * 
 * (6) ORDERED A LOT OF ONE ITEM
 * TODO: USE A MAX QUANTITIY METHOD TO FIND THE LARGEST QUANTITY OF AN ITEM IN A JOB
 * IF A PARTICULAR ITEM IS ORDERED (5+) TIMES?
 * THERE ARE LOTS OF 4S IN THE JOB SPREADSHEET BUT 5 AND 6 ARE UNCOMMON,
 * COULD BE DUE TO A MISTAKE WHEN ORDERING
 * 1-2 3-4 5+ ?
 *
 * 
 */
}
